config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'sessions#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/signup', to: 'users#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :workouts, only: [:create, :destroy, :show]
  resources :rounds, only: [:create, :destory,]
  resources :machines, only: [:create]
  resources :users do
    resources :workouts
  end
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    validates :name, presence: true, length: {maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}
    has_many :workouts, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    @workout = Workout.new
    @round = Round.new
    @machine = Machine.new
    @machine2 = Machine.new
    if current_user.workouts.first.rounds.count == 1 or current_user.workouts.first.rounds.count == 2
      @machine1round1 = current_user.workouts.first.rounds.first.machines.find_by(name: "Abdominal Crunch")
      @machine2round1 = current_user.workouts.first.rounds.first.machines.find_by(name: "Back Extension")
      @machine3round1 = current_user.workouts.first.rounds.first.machines.find_by(name: "Triceps Press")
      @machine4round1 = current_user.workouts.first.rounds.first.machines.find_by(name: "Biceps Curl")
      @machine5round1 = current_user.workouts.first.rounds.first.machines.find_by(name: "Shoulder Press")
      @machine6round1 = current_user.workouts.first.rounds.first.machines.find_by(name: "Lateral Raise")
      @machine7round1 = current_user.workouts.first.rounds.first.machines.find_by(name: "Row/Rear Deltoid")
      @machine8round1 = current_user.workouts.first.rounds.first.machines.find_by(name: "Chest Press")
      @machine9round1 = current_user.workouts.first.rounds.first.machines.find_by(name: "Hip Adduction")
      @machine10round1 = current_user.workouts.first.rounds.first.machines.find_by(name: "Hip Abduction")
      @machine11round1 = current_user.workouts.first.rounds.first.machines.find_by(name: "Calf Extension")
      @machine12round1 = current_user.workouts.first.rounds.first.machines.find_by(name: "Seated Leg Press")
      @machine13round1 = current_user.workouts.first.rounds.first.machines.find_by(name: "Seated Leg Curl")
      @machine14round1 = current_user.workouts.first.rounds.first.machines.find_by(name: "Leg Extension")
    end
    if current_user.workouts.first.rounds.count == 2
      @machine1round2 = current_user.workouts.first.rounds.last.machines.find_by(name: "Abdominal Crunch")
      @machine2round2 = current_user.workouts.first.rounds.last.machines.find_by(name: "Back Extension")
      @machine3round2 = current_user.workouts.first.rounds.last.machines.find_by(name: "Triceps Press")
      @machine4round2 = current_user.workouts.first.rounds.last.machines.find_by(name: "Biceps Curl")
      @machine5round2 = current_user.workouts.first.rounds.last.machines.find_by(name: "Shoulder Press")
      @machine6round2 = current_user.workouts.first.rounds.last.machines.find_by(name: "Lateral Raise")
      @machine7round2 = current_user.workouts.first.rounds.last.machines.find_by(name: "Row/Rear Deltoid")
      @machine8round2 = current_user.workouts.first.rounds.last.machines.find_by(name: "Chest Press")
      @machine9round2 = current_user.workouts.first.rounds.last.machines.find_by(name: "Hip Adduction")
      @machine10round2 = current_user.workouts.first.rounds.last.machines.find_by(name: "Hip Abduction")
      @machine11round2 = current_user.workouts.first.rounds.last.machines.find_by(name: "Calf Extension")
      @machine12round2 = current_user.workouts.first.rounds.last.machines.find_by(name: "Seated Leg Press")
      @machine13round2 = current_user.workouts.first.rounds.last.machines.find_by(name: "Seated Leg Curl")
      @machine14round2 = current_user.workouts.first.rounds.last.machines.find_by(name: "Leg Extension")
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Signup</h1>
<div class="full-screen">
    <div class="signup-form full-screen">
        <%= form_for(@user, url: signup_path) do |f| %>
            <%= render 'shared/error_messages' %>
            
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form_control' %>
            
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form_control' %>
            
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form_control' %>
            
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form_control' %>
            
            <%= f.submit "Create my account", class: "btn btn-primary" %>
            
            <p>Already have an account? Sign in <%= link_to 'here', login_path %></p>
        
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="profile-header">
    <h1>Welcome <% if @user.name == "Bruce Wayne" %>Batman, I mean, Bruce.<% else %><%= @user.name %><% end %></h1>
</div>
<div class="workouts">
    <% if @user.workouts.any? %>
        <%= render 'layouts/workout' %>
    <% else %>
        Yo! You need to create a workout!
        <div class="workout-form"><%= render 'shared/workout_form' %></div>
    <% end %>
</div>