config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'sessions#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/signup', to: 'users#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :workouts, only: [:create, :destroy, :show]
  resources :rounds, only: [:create, :destory,]
  resources :machines, only: [:create]
  resources :users do
    resources :workouts
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Workout App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_workout.html.erb
<div class="workout-controller">
    <div class="container">
        <div class="row">
            <div class="workout_date"><span class="badge badge-primary"><%= current_user.workouts.first.date.strftime("%-m / %e / %Y") %></span> Workout ID: <%= current_user.workouts.first.id %></div>
            <div class="workout-form"><%= render 'shared/workout_form' %></div>
        </div>
        <div class="row">
            <button type="button" class="btn btn-primary" style="clear: both; margin-bottom: 5px;" onclick="document.getElementById('set-info').style.display='none'; document.getElementById('show-button').style.display='block'; document.getElementById('hide-button').style.display='none'" id="hide-button">Hide Set Info</button>
            <button type="button" class="btn btn-primary" style="clear: both; margin-bottom: 5px; display: none;" onclick="document.getElementById('set-info').style.display='block'; document.getElementById('hide-button').style.display='block'; document.getElementById('show-button').style.display='none'" id="show-button">Show Set Info</button>
        </div>
        <div class="row">
            <div class="alert alert-info" role="alert" style="clear: both;" id="set-info">Set Count: <%= current_user.workouts.first.rounds.count %><% if current_user.workouts.first.rounds.count >= 1 %> | Set info = Set 1 id: <%= current_user.workouts.first.rounds.first.id %><% end %><% if current_user.workouts.first.rounds.count == 2 %> | Set 2 id: <%= current_user.workouts.first.rounds.last.id %><% end %></div>
        </div
    </div>
</div>
<div class="container workout-data">
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-2">Last Workout</div>
        <div class="col-sm-2"><% if current_user.workouts.first.rounds.count == 1 or current_user.workouts.first.rounds.count == 2 %>1st Set<% else %><%=render 'shared/new_round_button' %><% end %></div>
        <div class="col-sm-2"><% if current_user.workouts.first.rounds.count == 2 %>2nd Set<% elsif current_user.workouts.first.rounds.count == 1 %><%=render 'shared/new_round_button' %><% end %></div>
    </div>
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-1">Weight</div>
        <div class="col-sm-1">Reps</div>
        <div class="col-sm-1">Weight</div>
        <div class="col-sm-1">Reps</div>
        <div class="col-sm-1">Weight</div>
        <div class="col-sm-1">Reps</div>
    </div>
    <div class="row">
            <div class="col-sm-2">Abdominal Crunch</div>
            <div class="col-sm-1">¯\_(ツ)_/¯</div>
            <div class="col-sm-1">¯\_(ツ)_/¯</div>
            <% if current_user.workouts.first.rounds.count >= 1 and !@machine1round1 %><div class="col-sm-2"><%= render 'shared/machine1_form' %></div><% end %>
            <% if @machine1round1 %><div class="col-sm-1"><%= @machine1round1.weight %></div><div class="col-sm-1"><%= @machine1round1.reps %></div><% end %>
            <% if current_user.workouts.first.rounds.count == 2 and !@machine1round2 %><div class="col-sm-2"><%= render 'shared/machine1round2_form' %></div><% end %>
            <% if @machine1round2 %><div class="col-sm-1"><%= @machine1round2.weight %></div><div class="col-sm-1"><%= @machine1round2.reps %></div><% end %>
        </div>
    <div class="row">
            <div class="col-sm-2">Back Extension</div>
            <div class="col-sm-1">¯\_(ツ)_/¯</div>
            <div class="col-sm-1">¯\_(ツ)_/¯</div>
            <% if current_user.workouts.first.rounds.count >= 1 and !@machine2round1 %><div class="col-sm-2"><%= render 'shared/machine2_form' %></div><% end %>
            <% if @machine2round1 %><div class="col-sm-1"><%= @machine2round1.weight %></div><div class="col-sm-1"><%= @machine2round1.reps %></div><% end %>
            <% if current_user.workouts.first.rounds.count == 2 and !@machine2round2 %><div class="col-sm-2"><%= render 'shared/machine2round2_form' %></div><% end %>
            <% if @machine2round2 %><div class="col-sm-1"><%= @machine2round2.weight %></div><div class="col-sm-1"><%= @machine2round2.reps %></div><% end %>
        </div>
    <div class="row">
        <div class="col-sm-2">Triceps Press</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <% if current_user.workouts.first.rounds.count >= 1 and !@machine3round1 %><div class="col-sm-2"><%= render 'shared/machine3_form' %></div><% end %>
        <% if @machine3round1 %><div class="col-sm-1"><%= @machine3round1.weight %></div><div class="col-sm-1"><%= @machine3round1.reps %></div><% end %>
        <% if current_user.workouts.first.rounds.count == 2 and !@machine3round2 %><div class="col-sm-2"><%= render 'shared/machine3round2_form' %></div><% end %>
        <% if @machine3round2 %><div class="col-sm-1"><%= @machine3round2.weight %></div><div class="col-sm-1"><%= @machine3round2.reps %></div><% end %>
    </div>
    <div class="row">
        <div class="col-sm-2">Biceps Curl</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <% if current_user.workouts.first.rounds.count >= 1 and !@machine4round1 %><div class="col-sm-2"><%= render 'shared/machine4_form' %></div><% end %>
        <% if @machine4round1 %><div class="col-sm-1"><%= @machine4round1.weight %></div><div class="col-sm-1"><%= @machine4round1.reps %></div><% end %>
        <% if current_user.workouts.first.rounds.count == 2 and !@machine4round2 %><div class="col-sm-2"><%= render 'shared/machine4round2_form' %></div><% end %>
        <% if @machine4round2 %><div class="col-s-1"><%= @machine4round2.weight %></div><div class="col-sm-1"><%= @machine4round2.reps %></div><% end %>
    </div>
    <div class="row">
        <div class="col-sm-2">Shoulder Press</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <% if current_user.workouts.first.rounds.count >= 1 and !@machine5round1 %><div class="col-sm-2"><%= render 'shared/machine5_form' %></div><% end %>
        <% if @machine5round1 %><div class="col-sm-1"><%= @machine5round1.weight %></div><div class="col-sm-1"><%= @machine5round1.reps %></div><% end %>
        <% if current_user.workouts.first.rounds.count == 2 and !@machine5round2 %><div class="col-sm-2"><%= render 'shared/machine5round2_form' %></div><% end %>
        <% if @machine5round2 %><div class="col-sm-1"><%= @machine5round2.weight %></div><div class="col-sm-1"><%= @machine5round2.reps %></div><% end %>
    </div>
    <div class="row">
        <div class="col-sm-2">Lateral Raise</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <% if current_user.workouts.first.rounds.count >= 1 and !@machine6round1 %><div class="col-sm-2"><%= render 'shared/machine6_form' %></div><% end %>
        <% if @machine6round1 %><div class="col-sm-1"><%= @machine6round1.weight %></div><div class="col-sm-1"><%= @machine6round1.reps %></div><% end %>
        <% if current_user.workouts.first.rounds.count == 2 and !@machine6round2 %><div class="col-sm-2"><%= render 'shared/machine6round2_form' %></div><% end %>
        <% if @machine6round2 %><div class="col-sm-1"><%= @machine6round2.weight %></div><div class="col-sm-1"><%= @machine6round2.reps %></div><% end %>
    </div>
    <div class="row">
        <div class="col-sm-2">Row/Rear Deltoid</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <% if current_user.workouts.first.rounds.count >= 1 and !@machine7round1 %><div class="col-sm-2"><%= render 'shared/machine7_form' %></div><% end %>
        <% if @machine7round1 %><div class="col-sm-1"><%= @machine7round1.weight %></div><div class="col-sm-1"><%= @machine7round1.reps %></div><% end %>
        <% if current_user.workouts.first.rounds.count == 2 and !@machine7round2 %><div class="col-sm-2"><%= render 'shared/machine7round2_form' %></div><% end %>
        <% if @machine7round2 %><div class="col-sm-1"><%= @machine7round2.weight %></div><div class="col-sm-1"><%= @machine7round2.reps %></div><% end %>
    </div>
    <div class="row">
        <div class="col-sm-2">Chest Press</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <% if current_user.workouts.first.rounds.count >= 1 and !@machine8round1 %><div class="col-sm-2"><%= render 'shared/machine8_form' %></div><% end %>
        <% if @machine8round1 %><div class="col-sm-1"><%= @machine8round1.weight %></div><div class="col-sm-1"><%= @machine8round1.reps %></div><% end %>
        <% if current_user.workouts.first.rounds.count == 2 and !@machine8round2 %><div class="col-sm-2"><%= render 'shared/machine8round2_form' %></div><% end %>
        <% if @machine8round2 %><div class="col-sm-1"><%= @machine8round2.weight %></div><div class="col-sm-1"><%= @machine8round2.reps %></div><% end %>
    </div>
    <div class="row">
        <div class="col-sm-2">Hip Adduction</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <% if current_user.workouts.first.rounds.count >= 1 and !@machine9round1 %><div class="col-sm-2"><%= render 'shared/machine9_form' %></div><% end %>
        <% if @machine9round1 %><div class="col-sm-1"><%= @machine9round1.weight %></div><div class="col-sm-1"><%= @machine9round1.reps %></div><% end %>
        <% if current_user.workouts.first.rounds.count == 2 and !@machine9round2 %><div class="col-sm-2"><%= render 'shared/machine9round2_form' %></div><% end %>
        <% if @machine9round2 %><div class="col-sm-1"><%= @machine9round2.weight %></div><div class="col-sm-1"><%= @machine9round2.reps %></div><% end %>
    </div>
    <div class="row">
        <div class="col-sm-2">Hip Abduction</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <% if current_user.workouts.first.rounds.count >= 1 and !@machine10round1 %><div class="col-sm-2"><%= render 'shared/machine10_form' %></div><% end %>
        <% if @machine10round1 %><div class="col-sm-1"><%= @machine10round1.weight %></div><div class="col-sm-1"><%= @machine10round1.reps %></div><% end %>
        <% if current_user.workouts.first.rounds.count == 2 and !@machine10round2 %><div class="col-sm-2"><%= render 'shared/machine10round2_form' %></div><% end %>
        <% if @machine10round2 %><div class="col-sm-1"><%= @machine10round2.weight %></div><div class="col-sm-1"><%= @machine10round2.reps %></div><% end %>
    </div>
    <div class="row">
        <div class="col-sm-2">Calf Extension</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <% if current_user.workouts.first.rounds.count >= 1 and !@machine11round1 %><div class="col-sm-2"><%= render 'shared/machine11_form' %></div><% end %>
        <% if @machine11round1 %><div class="col-sm-1"><%= @machine11round1.weight %></div><div class="col-sm-1"><%= @machine11round1.reps %></div><% end %>
        <% if current_user.workouts.first.rounds.count == 2 and !@machine11round2 %><div class="col-sm-2"><%= render 'shared/machine11round2_form' %></div><% end %>
        <% if @machine11round2 %><div class="col-sm-1"><%= @machine11round2.weight %></div><div class="col-sm-1"><%= @machine11round2.reps %></div><% end %>
    </div>
    <div class="row">
        <div class="col-sm-2">Seated Leg Press</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <% if current_user.workouts.first.rounds.count >= 1 and !@machine12round1 %><div class="col-sm-2"><%= render 'shared/machine12_form' %></div><% end %>
        <% if @machine12round1 %><div class="col-sm-1"><%= @machine12round1.weight %></div><div class="col-sm-1"><%= @machine12round1.reps %></div><% end %>
        <% if current_user.workouts.first.rounds.count == 2 and !@machine12round2 %><div class="col-sm-2"><%= render 'shared/machine12round2_form' %></div><% end %>
        <% if @machine12round2 %><div class="col-sm-1"><%= @machine12round2.weight %></div><div class="col-sm-1"><%= @machine12round2.reps %></div><% end %>
    </div>
    <div class="row">
        <div class="col-sm-2">Seated Leg Curl</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <% if current_user.workouts.first.rounds.count >= 1 and !@machine13round1 %><div class="col-sm-2"><%= render 'shared/machine13_form' %></div><% end %>
        <% if @machine13round1 %><div class="col-sm-1"><%= @machine13round1.weight %></div><div class="col-sm-1"><%= @machine13round1.reps %></div><% end %>
        <% if current_user.workouts.first.rounds.count == 2 and !@machine13round2 %><div class="col-sm-2"><%= render 'shared/machine13round2_form' %></div><% end %>
        <% if @machine13round2 %><div class="col-sm-1"><%= @machine13round2.weight %></div><div class="col-sm-1"><%= @machine13round2.reps %></div><% end %>
    </div>
    <div class="row">
        <div class="col-sm-2">Leg Extension</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <div class="col-sm-1">¯\_(ツ)_/¯</div>
        <% if current_user.workouts.first.rounds.count >= 1 and !@machine14round1 %><div class="col-sm-2"><%= render 'shared/machine14_form' %></div><% end %>
        <% if @machine14round1 %><div class="col-sm-1"><%= @machine14round1.weight %></div><div class="col-sm-1"><%= @machine14round1.reps %></div><% end %>
        <% if current_user.workouts.first.rounds.count == 2 and !@machine14round2 %><div class="col-sm-2"><%= render 'shared/machine14round2_form' %></div><% end %>
        <% if @machine14round2 %><div class="col-sm-1"><%= @machine14round2.weight %></div><div class="col-sm-1"><%= @machine14round2.reps %></div><% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="full-screen">
  <head>
    <title>WorkoutApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-125032079-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-125032079-1');
    </script>

  </head>

  <body>
    <%= render 'layouts/header' %>
      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>